// <auto-generated />
using System;
using AssisTec.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssisTec.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609165159_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AssisTec.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_cliente")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnName("bairro")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnName("cep")
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnName("cidade")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Complemento")
                        .HasColumnName("complemento")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("cpf")
                        .HasColumnType("varchar(14) CHARACTER SET utf8mb4")
                        .HasMaxLength(14);

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnName("datanasc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("estado")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnName("numero")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnName("rua")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Telefone")
                        .HasColumnName("telefone")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("AssisTec.Models.ContasReceber", b =>
                {
                    b.Property<int>("id_conta_receber")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_conta_receber")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_emissao")
                        .HasColumnName("data_emissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("data_pagamento")
                        .HasColumnName("data_pagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_vencimento")
                        .HasColumnName("data_vencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int?>("id_forma_pagamento_fk")
                        .HasColumnType("int");

                    b.Property<int?>("id_os_fk")
                        .HasColumnType("int");

                    b.Property<string>("observacoes")
                        .HasColumnName("observacoes")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<decimal>("valor")
                        .HasColumnName("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasMaxLength(18);

                    b.HasKey("id_conta_receber");

                    b.HasIndex("id_forma_pagamento_fk");

                    b.HasIndex("id_os_fk");

                    b.ToTable("contas_receber");
                });

            modelBuilder.Entity("AssisTec.Models.Equipamento", b =>
                {
                    b.Property<int>("Id_equipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_equipamento")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnName("marca")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnName("modelo")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Numero_Serie")
                        .IsRequired()
                        .HasColumnName("numero_serie")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Observacoes")
                        .HasColumnName("observacoes")
                        .HasColumnType("text");

                    b.Property<string>("acessorios")
                        .HasColumnName("acessorios")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("estado_entrada")
                        .IsRequired()
                        .HasColumnName("estado_entrada")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id_equipamento");

                    b.ToTable("equipamentos");
                });

            modelBuilder.Entity("AssisTec.Models.OrdemServico", b =>
                {
                    b.Property<int>("id_os")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_os")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_abertura")
                        .HasColumnName("data_abertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnName("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("data_fechamento")
                        .HasColumnName("data_fechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("diagnostico")
                        .HasColumnName("diagnostico")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<int?>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int?>("id_equipamento")
                        .HasColumnType("int");

                    b.Property<int?>("id_tecnico")
                        .HasColumnType("int");

                    b.Property<string>("observacoes")
                        .HasColumnName("observacoes")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("problema_relatado")
                        .HasColumnName("problema_relatado")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<decimal>("valor_mao_obra")
                        .HasColumnName("valor_mao_obra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("valor_pecas")
                        .HasColumnName("valor_pecas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("valor_total")
                        .HasColumnName("valor_total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_os");

                    b.HasIndex("id_cliente");

                    b.HasIndex("id_equipamento");

                    b.HasIndex("id_tecnico");

                    b.ToTable("ordem_servico");
                });

            modelBuilder.Entity("AssisTec.Models.Pagamento", b =>
                {
                    b.Property<int>("Idforma_pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_forma_pagamento")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Idforma_pagamento");

                    b.ToTable("forma_pagamento");

                    b.HasData(
                        new
                        {
                            Idforma_pagamento = 1,
                            Descricao = "---"
                        },
                        new
                        {
                            Idforma_pagamento = 2,
                            Descricao = "Pix"
                        },
                        new
                        {
                            Idforma_pagamento = 3,
                            Descricao = "Cartão de Crédito / Débito"
                        },
                        new
                        {
                            Idforma_pagamento = 4,
                            Descricao = "Dinheiro"
                        });
                });

            modelBuilder.Entity("AssisTec.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnName("bairro")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnName("cep")
                        .HasColumnType("varchar(9) CHARACTER SET utf8mb4")
                        .HasMaxLength(9);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnName("cidade")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Complemento")
                        .HasColumnName("complemento")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("cpf")
                        .HasColumnType("varchar(14) CHARACTER SET utf8mb4")
                        .HasMaxLength(14);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("estado")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Nivel")
                        .HasColumnName("nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnName("numero")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnName("rua")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("senha")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasColumnName("telefone")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("AssisTec.Models.ContasReceber", b =>
                {
                    b.HasOne("AssisTec.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("id_forma_pagamento_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssisTec.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("id_os_fk")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AssisTec.Models.OrdemServico", b =>
                {
                    b.HasOne("AssisTec.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("id_cliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssisTec.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("id_equipamento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssisTec.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("id_tecnico")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
